#!/usr/bin/env bash
# Generates the TypeScript bindings from the .proto contract of record.
# The Go bindings are generated by server/scripts/generate.sh.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(cd ../.. && pwd)"
PLUGIN="${ROOT}/node_modules/.bin/protoc-gen-ts_proto"
if [[ "${OS:-}" == "Windows_NT" ]]; then
  PLUGIN="$(cygpath -w "${PLUGIN}.CMD")"
fi

protoc \
  --plugin="protoc-gen-ts_proto=${PLUGIN}" \
  --ts_proto_out=src/gen \
  --ts_proto_opt=esModuleInterop=true,forceLong=number,useOptionals=messages,outputServices=false,snakeToCamel=true,importSuffix=.js \
  --proto_path=proto \
  proto/room.proto

echo "generated src/gen/room.ts"
