import type { AssetManifest } from "@canvas-physics/client";

/** Every texture in this gallery is supplied by the consumer, not the engine. */
export const playgroundAssets: AssetManifest = {
  schemaVersion: 1,
  id: "item-playground",
  revision: "2026-08-23.5",
  sources: [
    { id: "workbench-art", src: "/workbench.svg", required: true },
    { id: "emoji-art", src: "/assets/party-emoji.svg", required: true },
    { id: "photo-art", src: "/assets/photo-card.svg", required: true },
    { id: "orb-mint-art", src: "/assets/orb-mint.svg", required: true },
    { id: "orb-coral-art", src: "/assets/orb-coral.svg", required: true },
    { id: "orb-violet-art", src: "/assets/orb-violet.svg", required: true },
    { id: "orb-pulse-art", src: "/assets/orb-pulse.svg", required: true },
    { id: "stamp-art", src: "/assets/system-stamp.svg", required: true },
    { id: "ball-art", src: "/assets/live-ball.svg", required: true },
    { id: "tile-mint-art", src: "/assets/tile-mint.svg", required: true },
    { id: "tile-coral-art", src: "/assets/tile-coral.svg", required: true },
    { id: "tile-violet-art", src: "/assets/tile-violet.svg", required: true },
    { id: "avatar-maker-art", src: "/assets/avatar-maker.svg", required: true },
    { id: "orb-custom-art", src: "/assets/orb-custom.svg", required: true },
    { id: "tile-custom-art", src: "/assets/tile-custom.svg", required: true },
    { id: "portal-pair-art", src: "/assets/portal-pair.svg", required: true },
    { id: "portal-pair-pulse-art", src: "/assets/portal-pair-pulse.svg", required: true },
  ],
  textures: [
    { id: "playground.workbench", sourceId: "workbench-art" },
    { id: "playground.emoji.party", sourceId: "emoji-art" },
    { id: "playground.photo", sourceId: "photo-art" },
    { id: "playground.orb.mint", sourceId: "orb-mint-art" },
    { id: "playground.orb.coral", sourceId: "orb-coral-art" },
    { id: "playground.orb.violet", sourceId: "orb-violet-art" },
    { id: "playground.orb.pulse", sourceId: "orb-pulse-art" },
    { id: "playground.system.stamp", sourceId: "stamp-art" },
    { id: "playground.ball", sourceId: "ball-art" },
    { id: "playground.tile.mint", sourceId: "tile-mint-art" },
    { id: "playground.tile.coral", sourceId: "tile-coral-art" },
    { id: "playground.tile.violet", sourceId: "tile-violet-art" },
    { id: "playground.avatar.maker", sourceId: "avatar-maker-art" },
    { id: "playground.orb.custom", sourceId: "orb-custom-art" },
    { id: "playground.tile.custom", sourceId: "tile-custom-art" },
    { id: "playground.portal.pair", sourceId: "portal-pair-art" },
    { id: "playground.portal.pairPulse", sourceId: "portal-pair-pulse-art" },
  ],
};
